SELECT*FROM rol;
SELECT*FROM usuario;
SELECT*FROM categoria;
SELECT*FROM producto;
SELECT*FROM direccion;
SELECT*FROM carrito;
SELECT*FROM carrito_detalle;
SELECT*FROM pedido;
SELECT*FROM pedido_detalle;
SELECT*FROM pago;
SELECT*FROM resenias;
SELECT*FROM promociones;
SELECT*FROM producto;
SELECT*FROM producto_promocion;
SELECT*FROM envio;
UPDATE envio SET fecha_entrega = NULL WHERE id_envio = 5;